MONGODB_HOST: mongodb.backend-alb-{{ env }}.chakra86.shop
REDIS_HOST: redis.backend-alb-{{ env }}.chakra86.shop
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.chakra86.shop
CART_HOST: cart.backend-alb-{{ env }}.chakra86.shop
USER_HOST: user.backend-alb-{{ env }}.chakra86.shop
RABBITMQ_HOST: rabbitmq.backend-alb-{{ env }}.chakra86.shop
MYSQL_HOST: mysql.backend-alb-{{ env }}.chakra86.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.chakra86.shop
PAYMENT_HOST: payment.backend-alb-{{ env }}.chakra86.shop
